### ISSUE TITLE
Infografía de Hilos en C#

### ISSUE THREAD

**Issue by JoseABCruz** [SistemasTecTlaxiaco/infografia-de-hilos-JoseABCruz#2]
[Hilos en Consola en C#.pdf](https://github.com/SistemasTecTlaxiaco/infografia-de-hilos-JoseABCruz/files/8375093/Hilos.en.Consola.en.C.pdf)

José Antonio Balbuena Cruz

**Comment by JudithReynaCS** [comment]
CALIFICACION:18%

**Comment by josealfredo79** [comment]
Bien hecho y revisado
